### ISSUE TITLE
Element `title` not allowed as child of element `head`

### ISSUE THREAD

**Issue by Annevd** [lisagjh/voorhoede#18]
Deze error kreeg ik na het doen van een HTML validator test:

![image](https://github.com/user-attachments/assets/e36e8920-0cb9-459c-8e62-231d59e463e1)

Dit komt omdat er 2 `title` elementen in je `head` staan. Je kan dit dus oplossen door een van de twee weg te halen.

**Comment by lisagjh** [comment]
fixed
