### ISSUE TITLE
Horizontal scroll bug

### ISSUE THREAD

**Issue by Annevd** [lisagjh/voorhoede#21]
Als het scherm niet breed genoeg is verschijnt er een horizontale overflow op de pagina:

<img width=500  src="https://github.com/user-attachments/assets/090622d4-1193-42e5-9f45-efd36acc5615">

In de inspector lijkt dit door de `padding` op het `header` element te komen. Hier zouden jullie nog naar kunnen kijken. Misschien de padding weghalen en/of op een ander element zetten?

**Comment by lisagjh** [comment]
fixed!
