### ISSUE TITLE
onduidelijk waar ik me bevindt

### ISSUE THREAD

**Issue by wingsvn** [lisagjh/voorhoede#30]
Het is nu nog niet duidelijk op welke pagina ik me bevindt wanneer ik navigeer naar de leden pagina. Misschien een titel/header en/of een focus state toevoegen aan de link op de navigatie bar?

**Comment by yujing-student** [comment]
Dit is toegevoegd

![image](https://github.com/user-attachments/assets/0e35a418-2522-460b-9aa9-c19b07010a1c)

zie hier de code:
https://github.com/lisagjh/voorhoede/blob/main/src/routes/members/%2Bpage.svelte
