### ISSUE TITLE
usertest 7-10

### ISSUE THREAD

**Issue by yujing-student** [lisagjh/voorhoede#32]
let niet op de error nan

vragen?

vind je deze pagina duidelijk
vind je het design overeenkomen met de pagina
wat zou je beter willen zien op deze pagina ?

**Comment by yujing-student** [comment]
Aantekeningen Usertest akiko


De foto moet beter 

De tekst komt overeen met het design

De header was duidelijk 

De nummers en hiring was niet helemaal aligngt

De hover mist nog 

De collega’s staat anders dan in het design
En collega’s moeten kwa tekst er nog bij gezet

**Comment by Akikosophia** [comment]
vragen?

vind je deze pagina duidelijk: Ja!
vind je het design overeenkomen met de pagina: Ja zeker, de huisstijl komt goed overheen
wat zou je beter willen zien op deze pagina ? De feedback punten die ik hierboven zijn aangegeven

**Comment by yujing-student** [comment]
Dit heb ik opgelost.

<h1>Foto te dicht langs de kant</h1>

De foto staat niet te dicht langs de kant.
![image](https://github.com/user-attachments/assets/82a68df0-17fb-4e1b-a14c-3b2e075ae4d1)

<h1>Afstand tekst en hiring</h1>

De tekst en de knop staan ook niet te ver uit elkaar en werknemers staat er ook hoeveel mensen er werken.

![image](https://github.com/user-attachments/assets/2f11f79a-efd3-42a1-a8e7-8303cc2e6bcc)


<h1>Hover toegevoegd</h1>
Ook heb ik een hover toegevoegd dat als iemand op details hovert dat de knop zwart word.

![image](https://github.com/user-attachments/assets/033165e3-1557-4090-ae8c-1502fa22205a)


![image](https://github.com/user-attachments/assets/7cd7e6ef-3874-4af3-b86d-773157514eee)
