### ISSUE TITLE
Restructure section structure and heading levels?

### ISSUE THREAD

**Issue by joostf** [lisagjh/voorhoede#36]
https://github.com/lisagjh/voorhoede/blob/4c22446969e5c4f70f0f2efaf3f7e2aad8bd9ada/src/lib/Member.svelte#L9-L47

An `article` in an `article` element, both with a `h2` elements doesn't seem logical to me. Consider nesting article elements in a section, with logical heading levels, like this:

```html
<section>
  <h2>...</h2>
  <article>
    <h3>...</h3>
    ...
  </article>
  <article>
    <h3>...</h3>
    ...
  </article>
  ...
</section>
````

**Comment by lisagjh** [comment]
@yujing-student  Wil jij hier nog naar kijken?

**Comment by yujing-student** [comment]
dit heb ik opgelost zie de commit 

https://github.com/lisagjh/voorhoede/commit/8b86441923886669f6ff50095966065cc7d8233a

**Comment by lisagjh** [comment]
Oke even gemist, top!
