### ISSUE TITLE
Code & design review

### ISSUE THREAD

**Issue by SamaraFellaDina** [lisagjh/voorhoede#47]
hi! Ik had nog een aantal notaties over je ontwerp @lisagjh 

* Het zou leuk zijn dat de eerste tekst het middelpunt is als je op de pagina komt, waarna al je scrollt kleiner word en de rest van de content duidelijk word
  * Duidelijker voor de flow
  * Heb je meteen iemand zijn aandacht 
* Bij je ervoor pagina is echt leuk dat je die smiley Hebt, misschien leuk om in te voegen om zo persoonlijker over te komen naar je gebruiker.

**Comment by lisagjh** [comment]
Toegepast in spike 2! Neem dit mee in Sprint 18.
